id: d7_workflow_config_transition
label: Migrate workflow transition configuration
audit: true
migration_tags:
  - Drupal 7
  - Workflow
source:
  plugin: d7_workflow_config_transition
process:
  id: ''
  label: label
  from_sid:
    -
      plugin: migration_lookup
      migration: d7_workflow_state
      source: sid
  to_sid:
    -
      plugin: migration_lookup
      migration: d7_workflow_state
      source: target_sid
  roles:
    plugin: migration_lookup
    migration: d7_user_role
    source: roles
destination:
  plugin: 'entity:workflow_config_transition'
migration_dependencies:
  required:
    - d7_workflow_state
    - d7_user_role
  optional:
    - d7_workflow_state
    - d7_user_role
